//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Classes
{
    public string eid { get; set; }
    public string sid { get; set; }
    public string c_no { get; set; }
    public Nullable<System.DateTime> time { get; set; }
    public string room { get; set; }
    public Nullable<double> grade { get; set; }

    public virtual Courses Courses { get; set; }
    public virtual Instructors Instructors { get; set; }
    public virtual Students Students { get; set; }
}

public partial class Courses
{
    public Courses()
    {
        this.Classes = new HashSet<Classes>();
    }

    public string c_no { get; set; }
    public string title { get; set; }
    public Nullable<int> credits { get; set; }

    public virtual ICollection<Classes> Classes { get; set; }
}

public partial class Instructors
{
    public Instructors()
    {
        this.Classes = new HashSet<Classes>();
    }

    public string eid { get; set; }
    public string name { get; set; }
    public string rank { get; set; }
    public string department { get; set; }

    public virtual ICollection<Classes> Classes { get; set; }
}

public partial class Students
{
    public Students()
    {
        this.Classes = new HashSet<Classes>();
    }

    public string sid { get; set; }
    public string name { get; set; }
    public string major { get; set; }
    public string tel { get; set; }
    public Nullable<System.DateTime> birthday { get; set; }

    public virtual ICollection<Classes> Classes { get; set; }
}
